name: 'Asana Git'
description: 'Asana Github Actions'
inputs:
  asana-pat:
    description: 'Asana Personal Access Token.'
    required: true
  targets:
    description: 'JSON array of objects having project and section where to move current task. Move task only if it exists in target project.'
    required: false
branding:
  icon: 'chevron-right'  
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'index.js'
